### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-health-check.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "ukfast/laravel-health-check": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by btaskew** [comment]
Any idea if this will be looked at anytime soon?

**Comment by rbibby** [comment]
All tested fine on a Laravel 10 project I've set up

@laravel-shift only issue I found with the automation was this comment https://github.com/ans-group/laravel-health-check/pull/75#issuecomment-1414550356 had our old vendor name `ukfast` rather than `ans-group`

**Comment by rbibby** [comment]
@btaskew I've merged this in but the tests have failed on the main branch. I'll have a look today and let you know when I've tagged the new version.

**Comment by btaskew** [comment]
Fantastic, thank you!

**Comment by rbibby** [comment]
@btaskew we've released v1.14.0 which has support for Laravel 10.

We've tested it on a couple of our projects and it all seems fine but let us know if you run into any problems.

**Pull request merged**
